### ISSUE TITLE
ESOLA 

### ISSUE THREAD

**Issue by evanmartua34** [zygurt/TSM#3]
what is the TSM parameter in Esola function? what should i fill this variable with?

**Comment by zygurt** [comment]
The TSM parameter in ESOLA, like in all of the methods, is the playback speed that you would like.  It takes any decimal value such that 0.5 = 50% , 1.0 = 100% (no change in speed), 2.0 = 200%.
I will update the comments at the top of the file for the next commit.

**Comment by zygurt** [comment]
This has now been updated.
