### ISSUE TITLE
ESOLA performance isn't good.

### ISSUE THREAD

**Issue by sunzj** [zygurt/TSM#5]
Hi, 

Thanks for these code! But I test ESOLA, the performance isn't good.

Actully there is a issue when call
ESOLA.m
```
%Generate epochs
epochs = ZFR(x, 1, fs, 2);
```
parameter didn't match with:
ZFR.m`function [ y ] = ZFR( s, fs, N_scale )`anyway, i change it to `epochs = ZFR(x, fs, 1);`
However, the result was just so so, i guess, it's worse than WSOLA.

So did i make a mistake when use ZFR, used the wrong parameter, or any other issues.

**Comment by zygurt** [comment]
Hi sunzj,
Yep, I agree that the ESOLA performance isn't great.  I improved on it with FESOLA, which is being published at the WASPAA 2019 conference in October.
Good catch on the code.
I'll push the current ESOLA, FESOLA and ZFR functions to the github.

**Comment by zygurt** [comment]
I've updated the functions, and checked that they work.  Let me know once you have them working successfully and I'll close this issue.

**Comment by sunzj** [comment]
@zygurt Thanks, it works!~

**Comment by zygurt** [comment]
Great. Closing the issue.
